//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/security/authentication_method.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const daqIntfID DAQ_AUTHENTICATION_METHOD_INTF_ID = { daq::IAuthenticationMethod::Id.Data1, daq::IAuthenticationMethod::Id.Data2, daq::IAuthenticationMethod::Id.Data3, daq::IAuthenticationMethod::Id.Data4_UInt64 };

void daqAuthenticationMethod_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_AUTHENTICATION_METHOD_INTF_ID;
}

daqErrCode daqAuthenticationMethod_getId(daqAuthenticationMethod* self, daqString** id)
{
    return reinterpret_cast<daq::IAuthenticationMethod*>(self)->getId(reinterpret_cast<daq::IString**>(id));
}

daqErrCode daqAuthenticationMethod_getFields(daqAuthenticationMethod* self, daqDict** fields)
{
    return reinterpret_cast<daq::IAuthenticationMethod*>(self)->getFields(reinterpret_cast<daq::IDict**>(fields));
}

daqErrCode daqAuthenticationMethod_getDescription(daqAuthenticationMethod* self, daqString** description)
{
    return reinterpret_cast<daq::IAuthenticationMethod*>(self)->getDescription(reinterpret_cast<daq::IString**>(description));
}

daqErrCode daqAuthenticationMethod_createAuthenticationMethod(daqAuthenticationMethod** obj, daqString* id, daqDict* fields, daqString* description)
{
    daq::IAuthenticationMethod* ptr = nullptr;
    daqErrCode err = daq::createAuthenticationMethod(&ptr, reinterpret_cast<daq::IString*>(id), reinterpret_cast<daq::IDict*>(fields), reinterpret_cast<daq::IString*>(description));
    *obj = reinterpret_cast<daqAuthenticationMethod*>(ptr);
    return err;
}
