//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/security/authentication_config.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const daqIntfID DAQ_AUTHENTICATION_CONFIG_INTF_ID = { daq::IAuthenticationConfig::Id.Data1, daq::IAuthenticationConfig::Id.Data2, daq::IAuthenticationConfig::Id.Data3, daq::IAuthenticationConfig::Id.Data4_UInt64 };

void daqAuthenticationConfig_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_AUTHENTICATION_CONFIG_INTF_ID;
}

daqErrCode daqAuthenticationConfig_getSelectedAuthenticationMethodId(daqAuthenticationConfig* self, daqString** authenticationMethodId)
{
    return reinterpret_cast<daq::IAuthenticationConfig*>(self)->getSelectedAuthenticationMethodId(reinterpret_cast<daq::IString**>(authenticationMethodId));
}

daqErrCode daqAuthenticationConfig_setAuthenticationMethodId(daqAuthenticationConfig* self, daqString* authenticationMethodId)
{
    return reinterpret_cast<daq::IAuthenticationConfig*>(self)->setAuthenticationMethodId(reinterpret_cast<daq::IString*>(authenticationMethodId));
}

daqErrCode daqAuthenticationConfig_getSupportedAuthenticationMethods(daqAuthenticationConfig* self, daqDict** descriptors)
{
    return reinterpret_cast<daq::IAuthenticationConfig*>(self)->getSupportedAuthenticationMethods(reinterpret_cast<daq::IDict**>(descriptors));
}

daqErrCode daqAuthenticationConfig_getSelectedCredentialProviderId(daqAuthenticationConfig* self, daqString** providerId)
{
    return reinterpret_cast<daq::IAuthenticationConfig*>(self)->getSelectedCredentialProviderId(reinterpret_cast<daq::IString**>(providerId));
}

daqErrCode daqAuthenticationConfig_setCredentialProviderId(daqAuthenticationConfig* self, daqString* providerId)
{
    return reinterpret_cast<daq::IAuthenticationConfig*>(self)->setCredentialProviderId(reinterpret_cast<daq::IString*>(providerId));
}

daqErrCode daqAuthenticationConfig_getSupportedCredentialProviderIds(daqAuthenticationConfig* self, daqList** providerIds)
{
    return reinterpret_cast<daq::IAuthenticationConfig*>(self)->getSupportedCredentialProviderIds(reinterpret_cast<daq::IList**>(providerIds));
}

daqErrCode daqAuthenticationConfig_getSuppliedSecret(daqAuthenticationConfig* self, daqPropertyObject** secret)
{
    return reinterpret_cast<daq::IAuthenticationConfig*>(self)->getSuppliedSecret(reinterpret_cast<daq::IPropertyObject**>(secret));
}

daqErrCode daqAuthenticationConfig_createAuthenticationConfig(daqAuthenticationConfig** obj, daqDict* credentialDescriptors, daqString* defaultAuthenticationMethodId, daqContext* context, daqString* typeId)
{
    daq::IAuthenticationConfig* ptr = nullptr;
    daqErrCode err = daq::createAuthenticationConfig(&ptr, reinterpret_cast<daq::IDict*>(credentialDescriptors), reinterpret_cast<daq::IString*>(defaultAuthenticationMethodId), reinterpret_cast<daq::IContext*>(context), reinterpret_cast<daq::IString*>(typeId));
    *obj = reinterpret_cast<daqAuthenticationConfig*>(ptr);
    return err;
}
