//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/security/authentication_method.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const daqIntfID DAQ_AUTHENTICATION_METHOD_INTF_ID = { daq::IAuthenticationMethod::Id.Data1, daq::IAuthenticationMethod::Id.Data2, daq::IAuthenticationMethod::Id.Data3, daq::IAuthenticationMethod::Id.Data4_UInt64 };

void daqAuthenticationMethod_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_AUTHENTICATION_METHOD_INTF_ID;
}

daqErrCode daqAuthenticationMethod_getId(daqAuthenticationMethod* self, daqString** id)
{
    return reinterpret_cast<daq::IAuthenticationMethod*>(self)->getId(reinterpret_cast<daq::IString**>(id));
}

daqErrCode daqAuthenticationMethod_getFormat(daqAuthenticationMethod* self, daqCredentialFormat* format)
{
    return reinterpret_cast<daq::IAuthenticationMethod*>(self)->getFormat(reinterpret_cast<daq::CredentialFormat*>(format));
}

daqErrCode daqAuthenticationMethod_getParameters(daqAuthenticationMethod* self, daqStruct** parameters)
{
    return reinterpret_cast<daq::IAuthenticationMethod*>(self)->getParameters(reinterpret_cast<daq::IStruct**>(parameters));
}

daqErrCode daqAuthenticationMethod_getDescription(daqAuthenticationMethod* self, daqString** description)
{
    return reinterpret_cast<daq::IAuthenticationMethod*>(self)->getDescription(reinterpret_cast<daq::IString**>(description));
}

daqErrCode daqAuthenticationMethod_createEmptyCredential(daqAuthenticationMethod* self, daqPropertyObject** credential)
{
    return reinterpret_cast<daq::IAuthenticationMethod*>(self)->createEmptyCredential(reinterpret_cast<daq::IPropertyObject**>(credential));
}

daqErrCode daqAuthenticationMethod_createKeyValueAuthenticationMethod(daqAuthenticationMethod** obj, daqString* id, daqDict* keys, daqString* description, daqTypeManager* typeManager, daqString* credentialClassName)
{
    daq::IAuthenticationMethod* ptr = nullptr;
    daqErrCode err = daq::createKeyValueAuthenticationMethod(&ptr, reinterpret_cast<daq::IString*>(id), reinterpret_cast<daq::IDict*>(keys), reinterpret_cast<daq::IString*>(description), reinterpret_cast<daq::ITypeManager*>(typeManager), reinterpret_cast<daq::IString*>(credentialClassName));
    *obj = reinterpret_cast<daqAuthenticationMethod*>(ptr);
    return err;
}

daqErrCode daqAuthenticationMethod_createStringAuthenticationMethod(daqAuthenticationMethod** obj, daqString* id, daqString* description, daqBool hidden, daqTypeManager* typeManager, daqString* credentialClassName)
{
    daq::IAuthenticationMethod* ptr = nullptr;
    daqErrCode err = daq::createStringAuthenticationMethod(&ptr, reinterpret_cast<daq::IString*>(id), reinterpret_cast<daq::IString*>(description), hidden, reinterpret_cast<daq::ITypeManager*>(typeManager), reinterpret_cast<daq::IString*>(credentialClassName));
    *obj = reinterpret_cast<daqAuthenticationMethod*>(ptr);
    return err;
}

daqErrCode daqAuthenticationMethod_createFilePathAuthenticationMethod(daqAuthenticationMethod** obj, daqString* id, daqString* description, daqTypeManager* typeManager, daqString* credentialClassName)
{
    daq::IAuthenticationMethod* ptr = nullptr;
    daqErrCode err = daq::createFilePathAuthenticationMethod(&ptr, reinterpret_cast<daq::IString*>(id), reinterpret_cast<daq::IString*>(description), reinterpret_cast<daq::ITypeManager*>(typeManager), reinterpret_cast<daq::IString*>(credentialClassName));
    *obj = reinterpret_cast<daqAuthenticationMethod*>(ptr);
    return err;
}

daqErrCode daqAuthenticationMethod_createNoneAuthenticationMethod(daqAuthenticationMethod** obj, daqString* id, daqString* description)
{
    daq::IAuthenticationMethod* ptr = nullptr;
    daqErrCode err = daq::createNoneAuthenticationMethod(&ptr, reinterpret_cast<daq::IString*>(id), reinterpret_cast<daq::IString*>(description));
    *obj = reinterpret_cast<daqAuthenticationMethod*>(ptr);
    return err;
}
