//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/security/authentication_config.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const daqIntfID DAQ_AUTHENTICATION_CONFIG_INTF_ID = { daq::IAuthenticationConfig::Id.Data1, daq::IAuthenticationConfig::Id.Data2, daq::IAuthenticationConfig::Id.Data3, daq::IAuthenticationConfig::Id.Data4_UInt64 };

void daqAuthenticationConfig_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_AUTHENTICATION_CONFIG_INTF_ID;
}

daqErrCode daqAuthenticationConfig_getSelectedAuthenticationMethodId(daqAuthenticationConfig* self, daqString** authenticationMethodId)
{
    return reinterpret_cast<daq::IAuthenticationConfig*>(self)->getSelectedAuthenticationMethodId(reinterpret_cast<daq::IString**>(authenticationMethodId));
}

daqErrCode daqAuthenticationConfig_setAuthenticationMethodId(daqAuthenticationConfig* self, daqString* authenticationMethodId)
{
    return reinterpret_cast<daq::IAuthenticationConfig*>(self)->setAuthenticationMethodId(reinterpret_cast<daq::IString*>(authenticationMethodId));
}

daqErrCode daqAuthenticationConfig_getSupportedAuthenticationMethods(daqAuthenticationConfig* self, daqDict** authenticationMethods)
{
    return reinterpret_cast<daq::IAuthenticationConfig*>(self)->getSupportedAuthenticationMethods(reinterpret_cast<daq::IDict**>(authenticationMethods));
}

daqErrCode daqAuthenticationConfig_getSuppliedCredential(daqAuthenticationConfig* self, daqPropertyObject** credential)
{
    return reinterpret_cast<daq::IAuthenticationConfig*>(self)->getSuppliedCredential(reinterpret_cast<daq::IPropertyObject**>(credential));
}

daqErrCode daqAuthenticationConfig_createAuthenticationConfig(daqAuthenticationConfig** obj, daqDict* authenticationMethods)
{
    daq::IAuthenticationConfig* ptr = nullptr;
    daqErrCode err = daq::createAuthenticationConfig(&ptr, reinterpret_cast<daq::IDict*>(authenticationMethods));
    *obj = reinterpret_cast<daqAuthenticationConfig*>(ptr);
    return err;
}
