//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/security/credential_request.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const daqIntfID DAQ_CREDENTIAL_REQUEST_INTF_ID = { daq::ICredentialRequest::Id.Data1, daq::ICredentialRequest::Id.Data2, daq::ICredentialRequest::Id.Data3, daq::ICredentialRequest::Id.Data4_UInt64 };

void daqCredentialRequest_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_CREDENTIAL_REQUEST_INTF_ID;
}

daqErrCode daqCredentialRequest_getComponentType(daqCredentialRequest* self, daqComponentType** componentType)
{
    return reinterpret_cast<daq::ICredentialRequest*>(self)->getComponentType(reinterpret_cast<daq::IComponentType**>(componentType));
}

daqErrCode daqCredentialRequest_getConnectionString(daqCredentialRequest* self, daqString** connectionString)
{
    return reinterpret_cast<daq::ICredentialRequest*>(self)->getConnectionString(reinterpret_cast<daq::IString**>(connectionString));
}

daqErrCode daqCredentialRequest_getMetaData(daqCredentialRequest* self, daqPropertyObject** metaData)
{
    return reinterpret_cast<daq::ICredentialRequest*>(self)->getMetaData(reinterpret_cast<daq::IPropertyObject**>(metaData));
}

daqErrCode daqCredentialRequest_getManufacturer(daqCredentialRequest* self, daqString** manufacturer)
{
    return reinterpret_cast<daq::ICredentialRequest*>(self)->getManufacturer(reinterpret_cast<daq::IString**>(manufacturer));
}

daqErrCode daqCredentialRequest_getSerialNumber(daqCredentialRequest* self, daqString** serialNumber)
{
    return reinterpret_cast<daq::ICredentialRequest*>(self)->getSerialNumber(reinterpret_cast<daq::IString**>(serialNumber));
}

daqErrCode daqCredentialRequest_getDescriptor(daqCredentialRequest* self, daqCredentialDescriptor** descriptor)
{
    return reinterpret_cast<daq::ICredentialRequest*>(self)->getDescriptor(reinterpret_cast<daq::ICredentialDescriptor**>(descriptor));
}
