//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/security/credential_provider.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const daqIntfID DAQ_CREDENTIAL_PROVIDER_INTF_ID = { daq::ICredentialProvider::Id.Data1, daq::ICredentialProvider::Id.Data2, daq::ICredentialProvider::Id.Data3, daq::ICredentialProvider::Id.Data4_UInt64 };

void daqCredentialProvider_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_CREDENTIAL_PROVIDER_INTF_ID;
}

daqErrCode daqCredentialProvider_getDescription(daqCredentialProvider* self, daqString** description)
{
    return reinterpret_cast<daq::ICredentialProvider*>(self)->getDescription(reinterpret_cast<daq::IString**>(description));
}

daqErrCode daqCredentialProvider_requestCredentials(daqCredentialProvider* self, daqCredentialRequest* request, daqDict** credentials)
{
    return reinterpret_cast<daq::ICredentialProvider*>(self)->requestCredentials(reinterpret_cast<daq::ICredentialRequest*>(request), reinterpret_cast<daq::IDict**>(credentials));
}

daqErrCode daqCredentialProvider_cacheCredentials(daqCredentialProvider* self, daqCredentialRequest* request, daqDict* credential)
{
    return reinterpret_cast<daq::ICredentialProvider*>(self)->cacheCredentials(reinterpret_cast<daq::ICredentialRequest*>(request), reinterpret_cast<daq::IDict*>(credential));
}

daqErrCode daqCredentialProvider_createCmdLineCredentialProvider(daqCredentialProvider** obj)
{
    daq::ICredentialProvider* ptr = nullptr;
    daqErrCode err = daq::createCmdLineCredentialProvider(&ptr);
    *obj = reinterpret_cast<daqCredentialProvider*>(ptr);
    return err;
}
