//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/security/credential_descriptor.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const daqIntfID DAQ_CREDENTIAL_DESCRIPTOR_INTF_ID = { daq::ICredentialDescriptor::Id.Data1, daq::ICredentialDescriptor::Id.Data2, daq::ICredentialDescriptor::Id.Data3, daq::ICredentialDescriptor::Id.Data4_UInt64 };

void daqCredentialDescriptor_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_CREDENTIAL_DESCRIPTOR_INTF_ID;
}

daqErrCode daqCredentialDescriptor_getAuthenticationMethodId(daqCredentialDescriptor* self, daqString** authenticationMethodId)
{
    return reinterpret_cast<daq::ICredentialDescriptor*>(self)->getAuthenticationMethodId(reinterpret_cast<daq::IString**>(authenticationMethodId));
}

daqErrCode daqCredentialDescriptor_getFormat(daqCredentialDescriptor* self, daqCredentialFormat* format)
{
    return reinterpret_cast<daq::ICredentialDescriptor*>(self)->getFormat(reinterpret_cast<daq::CredentialFormat*>(format));
}

daqErrCode daqCredentialDescriptor_getParameters(daqCredentialDescriptor* self, daqStruct** parameters)
{
    return reinterpret_cast<daq::ICredentialDescriptor*>(self)->getParameters(reinterpret_cast<daq::IStruct**>(parameters));
}

daqErrCode daqCredentialDescriptor_getDescription(daqCredentialDescriptor* self, daqString** description)
{
    return reinterpret_cast<daq::ICredentialDescriptor*>(self)->getDescription(reinterpret_cast<daq::IString**>(description));
}

daqErrCode daqCredentialDescriptor_createEmptySecret(daqCredentialDescriptor* self, daqPropertyObject** secret)
{
    return reinterpret_cast<daq::ICredentialDescriptor*>(self)->createEmptySecret(reinterpret_cast<daq::IPropertyObject**>(secret));
}

daqErrCode daqCredentialDescriptor_createKeyValueDescriptor(daqCredentialDescriptor** obj, daqString* id, daqDict* keys, daqString* description, daqTypeManager* typeManager, daqString* secretClassName)
{
    daq::ICredentialDescriptor* ptr = nullptr;
    daqErrCode err = daq::createKeyValueDescriptor(&ptr, reinterpret_cast<daq::IString*>(id), reinterpret_cast<daq::IDict*>(keys), reinterpret_cast<daq::IString*>(description), reinterpret_cast<daq::ITypeManager*>(typeManager), reinterpret_cast<daq::IString*>(secretClassName));
    *obj = reinterpret_cast<daqCredentialDescriptor*>(ptr);
    return err;
}

daqErrCode daqCredentialDescriptor_createStringDescriptor(daqCredentialDescriptor** obj, daqString* id, daqString* description, daqBool hidden, daqTypeManager* typeManager, daqString* secretClassName)
{
    daq::ICredentialDescriptor* ptr = nullptr;
    daqErrCode err = daq::createStringDescriptor(&ptr, reinterpret_cast<daq::IString*>(id), reinterpret_cast<daq::IString*>(description), hidden, reinterpret_cast<daq::ITypeManager*>(typeManager), reinterpret_cast<daq::IString*>(secretClassName));
    *obj = reinterpret_cast<daqCredentialDescriptor*>(ptr);
    return err;
}

daqErrCode daqCredentialDescriptor_createFilePathDescriptor(daqCredentialDescriptor** obj, daqString* id, daqString* description, daqTypeManager* typeManager, daqString* secretClassName)
{
    daq::ICredentialDescriptor* ptr = nullptr;
    daqErrCode err = daq::createFilePathDescriptor(&ptr, reinterpret_cast<daq::IString*>(id), reinterpret_cast<daq::IString*>(description), reinterpret_cast<daq::ITypeManager*>(typeManager), reinterpret_cast<daq::IString*>(secretClassName));
    *obj = reinterpret_cast<daqCredentialDescriptor*>(ptr);
    return err;
}

daqErrCode daqCredentialDescriptor_createNoneDescriptor(daqCredentialDescriptor** obj, daqString* id, daqString* description, daqTypeManager* typeManager)
{
    daq::ICredentialDescriptor* ptr = nullptr;
    daqErrCode err = daq::createNoneDescriptor(&ptr, reinterpret_cast<daq::IString*>(id), reinterpret_cast<daq::IString*>(description), reinterpret_cast<daq::ITypeManager*>(typeManager));
    *obj = reinterpret_cast<daqCredentialDescriptor*>(ptr);
    return err;
}
