//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/security/credential_provider.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const daqIntfID DAQ_CREDENTIAL_PROVIDER_INTF_ID = { daq::ICredentialProvider::Id.Data1, daq::ICredentialProvider::Id.Data2, daq::ICredentialProvider::Id.Data3, daq::ICredentialProvider::Id.Data4_UInt64 };

void daqCredentialProvider_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_CREDENTIAL_PROVIDER_INTF_ID;
}

daqErrCode daqCredentialProvider_getId(daqCredentialProvider* self, daqString** id)
{
    return reinterpret_cast<daq::ICredentialProvider*>(self)->getId(reinterpret_cast<daq::IString**>(id));
}

daqErrCode daqCredentialProvider_requestCredentials(daqCredentialProvider* self, daqCredentialRequest* request, daqPropertyObject** credentials)
{
    return reinterpret_cast<daq::ICredentialProvider*>(self)->requestCredentials(reinterpret_cast<daq::ICredentialRequest*>(request), reinterpret_cast<daq::IPropertyObject**>(credentials));
}

daqErrCode daqCredentialProvider_cacheCredentials(daqCredentialProvider* self, daqCredentialRequest* request, daqPropertyObject* secret)
{
    return reinterpret_cast<daq::ICredentialProvider*>(self)->cacheCredentials(reinterpret_cast<daq::ICredentialRequest*>(request), reinterpret_cast<daq::IPropertyObject*>(secret));
}

daqErrCode daqCredentialProvider_getSupportedFormats(daqCredentialProvider* self, daqList** formats)
{
    return reinterpret_cast<daq::ICredentialProvider*>(self)->getSupportedFormats(reinterpret_cast<daq::IList**>(formats));
}

daqErrCode daqCredentialProvider_createCmdLineCredentialProvider(daqCredentialProvider** obj)
{
    daq::ICredentialProvider* ptr = nullptr;
    daqErrCode err = daq::createCmdLineCredentialProvider(&ptr);
    *obj = reinterpret_cast<daqCredentialProvider*>(ptr);
    return err;
}

daqErrCode daqCredentialProvider_createFileCredentialProvider(daqCredentialProvider** obj)
{
    daq::ICredentialProvider* ptr = nullptr;
    daqErrCode err = daq::createFileCredentialProvider(&ptr);
    *obj = reinterpret_cast<daqCredentialProvider*>(ptr);
    return err;
}
