//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/security/credential_request_builder.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const daqIntfID DAQ_CREDENTIAL_REQUEST_BUILDER_INTF_ID = { daq::ICredentialRequestBuilder::Id.Data1, daq::ICredentialRequestBuilder::Id.Data2, daq::ICredentialRequestBuilder::Id.Data3, daq::ICredentialRequestBuilder::Id.Data4_UInt64 };

void daqCredentialRequestBuilder_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_CREDENTIAL_REQUEST_BUILDER_INTF_ID;
}

daqErrCode daqCredentialRequestBuilder_build(daqCredentialRequestBuilder* self, daqCredentialRequest** request)
{
    return reinterpret_cast<daq::ICredentialRequestBuilder*>(self)->build(reinterpret_cast<daq::ICredentialRequest**>(request));
}

daqErrCode daqCredentialRequestBuilder_setComponentType(daqCredentialRequestBuilder* self, daqComponentType* componentType)
{
    return reinterpret_cast<daq::ICredentialRequestBuilder*>(self)->setComponentType(reinterpret_cast<daq::IComponentType*>(componentType));
}

daqErrCode daqCredentialRequestBuilder_getComponentType(daqCredentialRequestBuilder* self, daqComponentType** componentType)
{
    return reinterpret_cast<daq::ICredentialRequestBuilder*>(self)->getComponentType(reinterpret_cast<daq::IComponentType**>(componentType));
}

daqErrCode daqCredentialRequestBuilder_setConnectionString(daqCredentialRequestBuilder* self, daqString* connectionString)
{
    return reinterpret_cast<daq::ICredentialRequestBuilder*>(self)->setConnectionString(reinterpret_cast<daq::IString*>(connectionString));
}

daqErrCode daqCredentialRequestBuilder_getConnectionString(daqCredentialRequestBuilder* self, daqString** connectionString)
{
    return reinterpret_cast<daq::ICredentialRequestBuilder*>(self)->getConnectionString(reinterpret_cast<daq::IString**>(connectionString));
}

daqErrCode daqCredentialRequestBuilder_setManufacturer(daqCredentialRequestBuilder* self, daqString* manufacturer)
{
    return reinterpret_cast<daq::ICredentialRequestBuilder*>(self)->setManufacturer(reinterpret_cast<daq::IString*>(manufacturer));
}

daqErrCode daqCredentialRequestBuilder_getManufacturer(daqCredentialRequestBuilder* self, daqString** manufacturer)
{
    return reinterpret_cast<daq::ICredentialRequestBuilder*>(self)->getManufacturer(reinterpret_cast<daq::IString**>(manufacturer));
}

daqErrCode daqCredentialRequestBuilder_setSerialNumber(daqCredentialRequestBuilder* self, daqString* serialNumber)
{
    return reinterpret_cast<daq::ICredentialRequestBuilder*>(self)->setSerialNumber(reinterpret_cast<daq::IString*>(serialNumber));
}

daqErrCode daqCredentialRequestBuilder_getSerialNumber(daqCredentialRequestBuilder* self, daqString** serialNumber)
{
    return reinterpret_cast<daq::ICredentialRequestBuilder*>(self)->getSerialNumber(reinterpret_cast<daq::IString**>(serialNumber));
}

daqErrCode daqCredentialRequestBuilder_addMetaDataProperty(daqCredentialRequestBuilder* self, daqProperty* property)
{
    return reinterpret_cast<daq::ICredentialRequestBuilder*>(self)->addMetaDataProperty(reinterpret_cast<daq::IProperty*>(property));
}

daqErrCode daqCredentialRequestBuilder_getMetaData(daqCredentialRequestBuilder* self, daqPropertyObject** property)
{
    return reinterpret_cast<daq::ICredentialRequestBuilder*>(self)->getMetaData(reinterpret_cast<daq::IPropertyObject**>(property));
}

daqErrCode daqCredentialRequestBuilder_setDescriptor(daqCredentialRequestBuilder* self, daqCredentialDescriptor* descriptor)
{
    return reinterpret_cast<daq::ICredentialRequestBuilder*>(self)->setDescriptor(reinterpret_cast<daq::ICredentialDescriptor*>(descriptor));
}

daqErrCode daqCredentialRequestBuilder_getDescriptor(daqCredentialRequestBuilder* self, daqCredentialDescriptor** descriptor)
{
    return reinterpret_cast<daq::ICredentialRequestBuilder*>(self)->getDescriptor(reinterpret_cast<daq::ICredentialDescriptor**>(descriptor));
}

daqErrCode daqCredentialRequestBuilder_createCredentialRequestBuilder(daqCredentialRequestBuilder** obj)
{
    daq::ICredentialRequestBuilder* ptr = nullptr;
    daqErrCode err = daq::createCredentialRequestBuilder(&ptr);
    *obj = reinterpret_cast<daqCredentialRequestBuilder*>(ptr);
    return err;
}
