//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/security/credential_field.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const daqIntfID DAQ_CREDENTIAL_FIELD_INTF_ID = { daq::ICredentialField::Id.Data1, daq::ICredentialField::Id.Data2, daq::ICredentialField::Id.Data3, daq::ICredentialField::Id.Data4_UInt64 };

void daqCredentialField_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_CREDENTIAL_FIELD_INTF_ID;
}

daqErrCode daqCredentialField_getId(daqCredentialField* self, daqString** id)
{
    return reinterpret_cast<daq::ICredentialField*>(self)->getId(reinterpret_cast<daq::IString**>(id));
}

daqErrCode daqCredentialField_getKind(daqCredentialField* self, daqCredentialFieldKind* kind)
{
    return reinterpret_cast<daq::ICredentialField*>(self)->getKind(reinterpret_cast<daq::CredentialFieldKind*>(kind));
}

daqErrCode daqCredentialField_getName(daqCredentialField* self, daqString** name)
{
    return reinterpret_cast<daq::ICredentialField*>(self)->getName(reinterpret_cast<daq::IString**>(name));
}

daqErrCode daqCredentialField_getMetadata(daqCredentialField* self, daqDict** metadata)
{
    return reinterpret_cast<daq::ICredentialField*>(self)->getMetadata(reinterpret_cast<daq::IDict**>(metadata));
}

daqErrCode daqCredentialField_isRequired(daqCredentialField* self, daqBool* required)
{
    return reinterpret_cast<daq::ICredentialField*>(self)->isRequired(required);
}

daqErrCode daqCredentialField_createCredentialField(daqCredentialField** obj, daqString* id, daqCredentialFieldKind kind, daqString* name, daqDict* metadata, daqBool required)
{
    daq::ICredentialField* ptr = nullptr;
    daqErrCode err = daq::createCredentialField(&ptr,
                                                 reinterpret_cast<daq::IString*>(id),
                                                 static_cast<daq::CredentialFieldKind>(kind),
                                                 reinterpret_cast<daq::IString*>(name),
                                                 reinterpret_cast<daq::IDict*>(metadata),
                                                 required);
    *obj = reinterpret_cast<daqCredentialField*>(ptr);
    return err;
}
