//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2026 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct daqAuthenticationConfig daqAuthenticationConfig;
    typedef struct daqString daqString;
    typedef struct daqPropertyObject daqPropertyObject;
    typedef struct daqDict daqDict;
    typedef struct daqList daqList;
    typedef struct daqContext daqContext;

    EXPORTED extern const daqIntfID DAQ_AUTHENTICATION_CONFIG_INTF_ID;
    void EXPORTED daqAuthenticationConfig_getInterfaceId(daqIntfID* intfId);

    daqErrCode EXPORTED daqAuthenticationConfig_getSelectedAuthenticationMethodId(daqAuthenticationConfig* self, daqString** authenticationMethodId);
    daqErrCode EXPORTED daqAuthenticationConfig_setAuthenticationMethodId(daqAuthenticationConfig* self, daqString* authenticationMethodId);
    daqErrCode EXPORTED daqAuthenticationConfig_getSupportedAuthenticationMethods(daqAuthenticationConfig* self, daqDict** descriptors);
    daqErrCode EXPORTED daqAuthenticationConfig_getSelectedCredentialProviderId(daqAuthenticationConfig* self, daqString** providerId);
    daqErrCode EXPORTED daqAuthenticationConfig_setCredentialProviderId(daqAuthenticationConfig* self, daqString* providerId);
    daqErrCode EXPORTED daqAuthenticationConfig_getSupportedCredentialProviderIds(daqAuthenticationConfig* self, daqList** providerIds);
    daqErrCode EXPORTED daqAuthenticationConfig_getSuppliedSecret(daqAuthenticationConfig* self, daqPropertyObject** secret);
    daqErrCode EXPORTED daqAuthenticationConfig_createAuthenticationConfig(daqAuthenticationConfig** obj, daqDict* credentialDescriptors, daqContext* context);

#ifdef __cplusplus
}
#endif
