//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2026 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct daqAuthenticationMethod daqAuthenticationMethod;
    typedef struct daqString daqString;
    typedef struct daqStruct daqStruct;
    typedef struct daqPropertyObject daqPropertyObject;
    typedef struct daqDict daqDict;
    typedef struct daqTypeManager daqTypeManager;

    EXPORTED extern const daqIntfID DAQ_AUTHENTICATION_METHOD_INTF_ID;
    void EXPORTED daqAuthenticationMethod_getInterfaceId(daqIntfID* intfId);

    daqErrCode EXPORTED daqAuthenticationMethod_getId(daqAuthenticationMethod* self, daqString** id);
    daqErrCode EXPORTED daqAuthenticationMethod_getFormat(daqAuthenticationMethod* self, daqCredentialFormat* format);
    daqErrCode EXPORTED daqAuthenticationMethod_getParameters(daqAuthenticationMethod* self, daqStruct** parameters);
    daqErrCode EXPORTED daqAuthenticationMethod_getDescription(daqAuthenticationMethod* self, daqString** description);
    daqErrCode EXPORTED daqAuthenticationMethod_createEmptySecret(daqAuthenticationMethod* self, daqPropertyObject** secret);
    daqErrCode EXPORTED daqAuthenticationMethod_createKeyValueAuthenticationMethod(daqAuthenticationMethod** obj, daqString* id, daqDict* keys, daqString* description, daqTypeManager* typeManager, daqString* secretClassName);
    daqErrCode EXPORTED daqAuthenticationMethod_createStringAuthenticationMethod(daqAuthenticationMethod** obj, daqString* id, daqString* description, daqBool hidden, daqTypeManager* typeManager, daqString* secretClassName);
    daqErrCode EXPORTED daqAuthenticationMethod_createFilePathAuthenticationMethod(daqAuthenticationMethod** obj, daqString* id, daqString* description, daqTypeManager* typeManager, daqString* secretClassName);
    daqErrCode EXPORTED daqAuthenticationMethod_createNoneAuthenticationMethod(daqAuthenticationMethod** obj, daqString* id, daqString* description);

#ifdef __cplusplus
}
#endif
