//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2026 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct daqCredentialDescriptor daqCredentialDescriptor;
    typedef struct daqString daqString;
    typedef struct daqStruct daqStruct;
    typedef struct daqPropertyObject daqPropertyObject;
    typedef struct daqDict daqDict;
    typedef struct daqTypeManager daqTypeManager;

    EXPORTED extern const daqIntfID DAQ_CREDENTIAL_DESCRIPTOR_INTF_ID;
    void EXPORTED daqCredentialDescriptor_getInterfaceId(daqIntfID* intfId);

    daqErrCode EXPORTED daqCredentialDescriptor_getAuthenticationMethodId(daqCredentialDescriptor* self, daqString** authenticationMethodId);
    daqErrCode EXPORTED daqCredentialDescriptor_getFormat(daqCredentialDescriptor* self, daqCredentialFormat* format);
    daqErrCode EXPORTED daqCredentialDescriptor_getParameters(daqCredentialDescriptor* self, daqStruct** parameters);
    daqErrCode EXPORTED daqCredentialDescriptor_getDescription(daqCredentialDescriptor* self, daqString** description);
    daqErrCode EXPORTED daqCredentialDescriptor_createEmptySecret(daqCredentialDescriptor* self, daqPropertyObject** secret);
    daqErrCode EXPORTED daqCredentialDescriptor_createKeyValueDescriptor(daqCredentialDescriptor** obj, daqString* id, daqDict* keys, daqString* description, daqTypeManager* typeManager, daqString* secretClassName);
    daqErrCode EXPORTED daqCredentialDescriptor_createStringDescriptor(daqCredentialDescriptor** obj, daqString* id, daqString* description, daqBool hidden, daqTypeManager* typeManager, daqString* secretClassName);
    daqErrCode EXPORTED daqCredentialDescriptor_createFilePathDescriptor(daqCredentialDescriptor** obj, daqString* id, daqString* description, daqTypeManager* typeManager, daqString* secretClassName);
    daqErrCode EXPORTED daqCredentialDescriptor_createNoneDescriptor(daqCredentialDescriptor** obj, daqString* id, daqString* description);

#ifdef __cplusplus
}
#endif
