//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2026 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct daqCredentialField daqCredentialField;
    typedef struct daqString daqString;
    typedef struct daqDict daqDict;

    EXPORTED extern const daqIntfID DAQ_CREDENTIAL_FIELD_INTF_ID;
    void EXPORTED daqCredentialField_getInterfaceId(daqIntfID* intfId);

    daqErrCode EXPORTED daqCredentialField_getId(daqCredentialField* self, daqString** id);
    daqErrCode EXPORTED daqCredentialField_getKind(daqCredentialField* self, daqCredentialFieldKind* kind);
    daqErrCode EXPORTED daqCredentialField_getName(daqCredentialField* self, daqString** name);
    daqErrCode EXPORTED daqCredentialField_getMetadata(daqCredentialField* self, daqDict** metadata);
    daqErrCode EXPORTED daqCredentialField_isRequired(daqCredentialField* self, daqBool* required);
    daqErrCode EXPORTED daqCredentialField_createCredentialField(daqCredentialField** obj, daqString* id, daqCredentialFieldKind kind, daqString* name, daqDict* metadata, daqBool required);

#ifdef __cplusplus
}
#endif
