//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2026 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct daqCredentialProvider daqCredentialProvider;
    typedef struct daqString daqString;
    typedef struct daqCredentialRequest daqCredentialRequest;
    typedef struct daqPropertyObject daqPropertyObject;
    typedef struct daqList daqList;

    EXPORTED extern const daqIntfID DAQ_CREDENTIAL_PROVIDER_INTF_ID;
    void EXPORTED daqCredentialProvider_getInterfaceId(daqIntfID* intfId);

    daqErrCode EXPORTED daqCredentialProvider_getId(daqCredentialProvider* self, daqString** id);
    daqErrCode EXPORTED daqCredentialProvider_requestCredentials(daqCredentialProvider* self, daqCredentialRequest* request, daqPropertyObject** credentials);
    daqErrCode EXPORTED daqCredentialProvider_cacheCredentials(daqCredentialProvider* self, daqCredentialRequest* request, daqPropertyObject* secret);
    daqErrCode EXPORTED daqCredentialProvider_getSupportedFormats(daqCredentialProvider* self, daqList** formats);
    daqErrCode EXPORTED daqCredentialProvider_createCmdLineCredentialProvider(daqCredentialProvider** obj);
    daqErrCode EXPORTED daqCredentialProvider_createFileCredentialProvider(daqCredentialProvider** obj);

#ifdef __cplusplus
}
#endif
