//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2026 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct daqCredentialRequestBuilder daqCredentialRequestBuilder;
    typedef struct daqCredentialRequest daqCredentialRequest;
    typedef struct daqComponentType daqComponentType;
    typedef struct daqString daqString;
    typedef struct daqProperty daqProperty;
    typedef struct daqPropertyObject daqPropertyObject;
    typedef struct daqCredentialDescriptor daqCredentialDescriptor;

    EXPORTED extern const daqIntfID DAQ_CREDENTIAL_REQUEST_BUILDER_INTF_ID;
    void EXPORTED daqCredentialRequestBuilder_getInterfaceId(daqIntfID* intfId);

    daqErrCode EXPORTED daqCredentialRequestBuilder_build(daqCredentialRequestBuilder* self, daqCredentialRequest** request);
    daqErrCode EXPORTED daqCredentialRequestBuilder_setComponentType(daqCredentialRequestBuilder* self, daqComponentType* componentType);
    daqErrCode EXPORTED daqCredentialRequestBuilder_getComponentType(daqCredentialRequestBuilder* self, daqComponentType** componentType);
    daqErrCode EXPORTED daqCredentialRequestBuilder_setConnectionString(daqCredentialRequestBuilder* self, daqString* connectionString);
    daqErrCode EXPORTED daqCredentialRequestBuilder_getConnectionString(daqCredentialRequestBuilder* self, daqString** connectionString);
    daqErrCode EXPORTED daqCredentialRequestBuilder_setManufacturer(daqCredentialRequestBuilder* self, daqString* manufacturer);
    daqErrCode EXPORTED daqCredentialRequestBuilder_getManufacturer(daqCredentialRequestBuilder* self, daqString** manufacturer);
    daqErrCode EXPORTED daqCredentialRequestBuilder_setSerialNumber(daqCredentialRequestBuilder* self, daqString* serialNumber);
    daqErrCode EXPORTED daqCredentialRequestBuilder_getSerialNumber(daqCredentialRequestBuilder* self, daqString** serialNumber);
    daqErrCode EXPORTED daqCredentialRequestBuilder_addMetaDataProperty(daqCredentialRequestBuilder* self, daqProperty* property);
    daqErrCode EXPORTED daqCredentialRequestBuilder_getMetaData(daqCredentialRequestBuilder* self, daqPropertyObject** property);
    daqErrCode EXPORTED daqCredentialRequestBuilder_setDescriptor(daqCredentialRequestBuilder* self, daqCredentialDescriptor* descriptor);
    daqErrCode EXPORTED daqCredentialRequestBuilder_getDescriptor(daqCredentialRequestBuilder* self, daqCredentialDescriptor** descriptor);
    daqErrCode EXPORTED daqCredentialRequestBuilder_createCredentialRequestBuilder(daqCredentialRequestBuilder** obj);

#ifdef __cplusplus
}
#endif
